version: "3.5"

services:
  apache-arrow:
    build:
      context: .
      dockerfile: dockerfiles/apache-arrow.dockerfile
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-apache-arrow-test.sh

  arch-linux:
    build:
      context: .
      dockerfile: dockerfiles/arch-linux.dockerfile
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  centos-7:
    build:
      context: .
      dockerfile: dockerfiles/centos-7.dockerfile
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  centos-8:
    build:
      context: .
      dockerfile: dockerfiles/centos-7.dockerfile
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  fedora-rawhide:
    build:
      context: .
      dockerfile: dockerfiles/fedora-rawhide.dockerfile
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  ruby-2.6:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        RUBY_VERSION: "2.6"
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  ruby-2.7:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        RUBY_VERSION: "2.7"
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  ruby-3.0:
    build:
      context: .
      dockerfile: dockerfiles/ruby.dockerfile
      args:
        RUBY_VERSION: "3.0"
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  ubuntu-18.04:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu-18.04.dockerfile
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh

  ubuntu-20.04:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu-20.04.dockerfile
    volumes:
      - .:/ruby-gnome:delegated
    command:
      /ruby-gnome/dockerfiles/run-test.sh
